// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.7.1
// source: protofolder/parkir.proto

package protofolder

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ServerReply) Reset() {
	*x = ServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofolder_parkir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply) ProtoMessage() {}

func (x *ServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_protofolder_parkir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply.ProtoReflect.Descriptor instead.
func (*ServerReply) Descriptor() ([]byte, []int) {
	return file_protofolder_parkir_proto_rawDescGZIP(), []int{0}
}

func (x *ServerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Parker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parkid    string `protobuf:"bytes,1,opt,name=parkid,proto3" json:"parkid,omitempty"`
	Kendaraan string `protobuf:"bytes,2,opt,name=kendaraan,proto3" json:"kendaraan,omitempty"`
	Platno    string `protobuf:"bytes,3,opt,name=platno,proto3" json:"platno,omitempty"`
}

func (x *Parker) Reset() {
	*x = Parker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofolder_parkir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parker) ProtoMessage() {}

func (x *Parker) ProtoReflect() protoreflect.Message {
	mi := &file_protofolder_parkir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parker.ProtoReflect.Descriptor instead.
func (*Parker) Descriptor() ([]byte, []int) {
	return file_protofolder_parkir_proto_rawDescGZIP(), []int{1}
}

func (x *Parker) GetParkid() string {
	if x != nil {
		return x.Parkid
	}
	return ""
}

func (x *Parker) GetKendaraan() string {
	if x != nil {
		return x.Kendaraan
	}
	return ""
}

func (x *Parker) GetPlatno() string {
	if x != nil {
		return x.Platno
	}
	return ""
}

type Parkid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parkid string `protobuf:"bytes,1,opt,name=parkid,proto3" json:"parkid,omitempty"`
}

func (x *Parkid) Reset() {
	*x = Parkid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofolder_parkir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parkid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parkid) ProtoMessage() {}

func (x *Parkid) ProtoReflect() protoreflect.Message {
	mi := &file_protofolder_parkir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parkid.ProtoReflect.Descriptor instead.
func (*Parkid) Descriptor() ([]byte, []int) {
	return file_protofolder_parkir_proto_rawDescGZIP(), []int{2}
}

func (x *Parkid) GetParkid() string {
	if x != nil {
		return x.Parkid
	}
	return ""
}

type Nota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Masuk     string `protobuf:"bytes,1,opt,name=masuk,proto3" json:"masuk,omitempty"`
	Keluar    string `protobuf:"bytes,2,opt,name=keluar,proto3" json:"keluar,omitempty"`
	Kendaraan string `protobuf:"bytes,3,opt,name=kendaraan,proto3" json:"kendaraan,omitempty"`
	Platno    string `protobuf:"bytes,4,opt,name=platno,proto3" json:"platno,omitempty"`
	Biaya     int32  `protobuf:"varint,5,opt,name=biaya,proto3" json:"biaya,omitempty"`
}

func (x *Nota) Reset() {
	*x = Nota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofolder_parkir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nota) ProtoMessage() {}

func (x *Nota) ProtoReflect() protoreflect.Message {
	mi := &file_protofolder_parkir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nota.ProtoReflect.Descriptor instead.
func (*Nota) Descriptor() ([]byte, []int) {
	return file_protofolder_parkir_proto_rawDescGZIP(), []int{3}
}

func (x *Nota) GetMasuk() string {
	if x != nil {
		return x.Masuk
	}
	return ""
}

func (x *Nota) GetKeluar() string {
	if x != nil {
		return x.Keluar
	}
	return ""
}

func (x *Nota) GetKendaraan() string {
	if x != nil {
		return x.Kendaraan
	}
	return ""
}

func (x *Nota) GetPlatno() string {
	if x != nil {
		return x.Platno
	}
	return ""
}

func (x *Nota) GetBiaya() int32 {
	if x != nil {
		return x.Biaya
	}
	return 0
}

var File_protofolder_parkir_proto protoreflect.FileDescriptor

var file_protofolder_parkir_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x27, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x56, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65,
	0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b,
	0x65, 0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x74,
	0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x74, 0x6e, 0x6f,
	0x22, 0x20, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x6b,
	0x69, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x61, 0x73, 0x75, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x73, 0x75,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x6e,
	0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65,
	0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x74, 0x6e,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x74, 0x6e, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x69, 0x61, 0x79, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x62, 0x69, 0x61, 0x79, 0x61, 0x32, 0xb0, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x40, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x70,
	0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x6b, 0x49, 0x44,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69,
	0x72, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x72, 0x6b, 0x46, 0x65, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69,
	0x72, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x1a, 0x0c, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69,
	0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x61, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofolder_parkir_proto_rawDescOnce sync.Once
	file_protofolder_parkir_proto_rawDescData = file_protofolder_parkir_proto_rawDesc
)

func file_protofolder_parkir_proto_rawDescGZIP() []byte {
	file_protofolder_parkir_proto_rawDescOnce.Do(func() {
		file_protofolder_parkir_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofolder_parkir_proto_rawDescData)
	})
	return file_protofolder_parkir_proto_rawDescData
}

var file_protofolder_parkir_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protofolder_parkir_proto_goTypes = []interface{}{
	(*ServerReply)(nil), // 0: parkir.ServerReply
	(*Parker)(nil),      // 1: parkir.Parker
	(*Parkid)(nil),      // 2: parkir.Parkid
	(*Nota)(nil),        // 3: parkir.Nota
	(*empty.Empty)(nil), // 4: google.protobuf.Empty
}
var file_protofolder_parkir_proto_depIdxs = []int32{
	4, // 0: parkir.Connect.ConnectToServer:input_type -> google.protobuf.Empty
	4, // 1: parkir.Connect.GetParkID:input_type -> google.protobuf.Empty
	1, // 2: parkir.Connect.GetParkFee:input_type -> parkir.Parker
	0, // 3: parkir.Connect.ConnectToServer:output_type -> parkir.ServerReply
	2, // 4: parkir.Connect.GetParkID:output_type -> parkir.Parkid
	3, // 5: parkir.Connect.GetParkFee:output_type -> parkir.Nota
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofolder_parkir_proto_init() }
func file_protofolder_parkir_proto_init() {
	if File_protofolder_parkir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofolder_parkir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofolder_parkir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofolder_parkir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parkid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofolder_parkir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofolder_parkir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofolder_parkir_proto_goTypes,
		DependencyIndexes: file_protofolder_parkir_proto_depIdxs,
		MessageInfos:      file_protofolder_parkir_proto_msgTypes,
	}.Build()
	File_protofolder_parkir_proto = out.File
	file_protofolder_parkir_proto_rawDesc = nil
	file_protofolder_parkir_proto_goTypes = nil
	file_protofolder_parkir_proto_depIdxs = nil
}
